In [1]:
import pandas as pd

In [2]:
fifa = pd.read_csv("data.csv")
fifa

,Unnamed: 0,Name,Age,Nationality,Overall,Potential,Club,Value,Preferred Foot,International Reputation,...,SprintSpeed,ShotPower,Jumping,Stamina,Strength,Aggression,Vision,StandingTackle,GKPositioning,GKReflexes
0,0,L. Messi,31,Argentina,94,94,FC Barcelona,€110.5M,Left,5.0,...,86.0,85.0,68.0,72.0,59.0,48.0,94.0,28.0,14.0,8.0
1,1,Cristiano Ronaldo,33,Portugal,94,94,Juventus,€77M,Right,5.0,...,91.0,95.0,95.0,88.0,79.0,63.0,82.0,31.0,14.0,11.0
2,2,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,€118.5M,Right,5.0,...,90.0,80.0,61.0,81.0,49.0,56.0,87.0,24.0,15.0,11.0
3,3,De Gea,27,Spain,91,93,Manchester United,€72M,Right,4.0,...,58.0,31.0,67.0,43.0,64.0,38.0,68.0,21.0,88.0,94.0
4,4,K. De Bruyne,27,Belgium,91,92,Manchester City,€102M,Right,4.0,...,76.0,91.0,63.0,90.0,75.0,76.0,94.0,58.0,10.0,13.0
5,5,E. Hazard,27,Belgium,91,91,Chelsea,€93M,Right,4.0,...,88.0,82.0,56.0,83.0,66.0,54.0,89.0,27.0,8.0,8.0
6,6,L. Modrić,32,Croatia,91,91,Real Madrid,€67M,Right,4.0,...,72.0,79.0,68.0,89.0,58.0,62.0,92.0,76.0,14.0,9.0
7,7,L. Suárez,31,Uruguay,91,91,FC Barcelona,€80M,Right,5.0,...,75.0,86.0,69.0,90.0,83.0,87.0,84.0,45.0,33.0,37.0
8,8,Sergio Ramos,32,Spain,91,91,Real Madrid,€51M,Right,4.0,...,75.0,79.0,93.0,84.0,83.0,88.0,63.0,92.0,7.0,11.0
9,9,J. Oblak,25,Slovenia,90,93,Atlético Madrid,€68M,Right,3.0,...,60.0,22.0,76.0,41.0,78.0,34.0,70.0,12.0,88.0,89.0
10,10,R. Lewandowski,29,Poland,90,90,FC Bayern München,€77M,Right,4.0,...,78.0,88.0,84.0,78.0,84.0,80.0,77.0,42.0,8.0,10.0
11,11,T. Kroos,28,Germany,90,90,Real Madrid,€76.5M,Right,4.0,...,62.0,87.0,30.0,75.0,73.0,60.0,86.0,79.0,7.0,10.0
12,12,D. Godín,32,Uruguay,90,90,Atlético Madrid,€44M,Right,3.0,...,68.0,67.0,91.0,66.0,88.0,89.0,52.0,89.0,5.0,15.0
13,13,David Silva,32,Spain,90,90,Manchester City,€60M,Left,4.0,...,64.0,72.0,64.0,78.0,52.0,57.0,92.0,53.0,6.0,12.0
14,14,N. Kanté,27,France,89,90,Chelsea,€63M,Right,3.0,...,78.0,71.0,77.0,96.0,76.0,90.0,79.0,91.0,7.0,10.0
15,15,P. Dybala,24,Argentina,89,94,Juventus,€89M,Left,3.0,...,83.0,82.0,75.0,80.0,65.0,48.0,87.0,20.0,5.0,8.0
16,16,H. Kane,24,England,89,91,Tottenham Hotspur,€83.5M,Right,3.0,...,72.0,88.0,78.0,89.0,84.0,76.0,80.0,36.0,14.0,11.0
17,17,A. Griezmann,27,France,89,90,Atlético Madrid,€78M,Left,4.0,...,85.0,80.0,90.0,83.0,62.0,69.0,83.0,47.0,13.0,14.0
18,18,M. ter Stegen,26,Germany,89,92,FC Barcelona,€58M,Right,3.0,...,50.0,22.0,79.0,35.0,79.0,43.0,69.0,13.0,85.0,90.0
19,19,T. Courtois,26,Belgium,89,90,Real Madrid,€53.5M,Left,4.0,...,52.0,36.0,68.0,38.0,70.0,23.0,44.0,18.0,86.0,88.0
20,20,Sergio Busquets,29,Spain,89,89,FC Barcelona,€51.5M,Right,4.0,...,52.0,61.0,66.0,86.0,77.0,85.0,87.0,86.0,9.0,13.0
21,21,E. Cavani,31,Uruguay,89,89,Paris Saint-Germain,€60M,Right,4.0,...,76.0,87.0,88.0,92.0,78.0,84.0,77.0,45.0,13.0,10.0
22,22,M. Neuer,32,Germany,89,89,FC Bayern München,€38M,Right,5.0,...,60.0,25.0,77.0,43.0,80.0,29.0,70.0,10.0,87.0,87.0
23,23,S. Agüero,30,Argentina,89,89,Manchester City,€64.5M,Right,4.0,...,80.0,88.0,81.0,76.0,73.0,65.0,83.0,20.0,11.0,14.0
24,24,G. Chiellini,33,Italy,89,89,Juventus,€27M,Left,4.0,...,75.0,78.0,89.0,65.0,89.0,92.0,50.0,93.0,4.0,3.0
25,25,K. Mbappé,19,France,88,95,Paris Saint-Germain,€81M,Right,3.0,...,96.0,79.0,75.0,83.0,71.0,62.0,82.0,34.0,11.0,6.0
26,26,M. Salah,26,Egypt,88,89,Liverpool,€69.5M,Left,3.0,...,91.0,77.0,68.0,84.0,70.0,63.0,82.0,43.0,11.0,14.0
27,27,Casemiro,26,Brazil,88,90,Real Madrid,€59.5M,Right,3.0,...,65.0,86.0,88.0,87.0,89.0,87.0,77.0,90.0,12.0,12.0
28,28,J. Rodríguez,26,Colombia,88,89,FC Bayern München,€69.5M,Left,4.0,...,67.0,86.0,54.0,70.0,68.0,64.0,89.0,41.0,5.0,14.0
29,29,L. Insigne,27,Italy,88,88,Napoli,€62M,Right,3.0,...,86.0,75.0,53.0,75.0,44.0,34.0,87.0,24.0,9.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18177,18177,R. Roache,18,Republic of Ireland,48,69,Blackpool,€70K,Right,1.0,...,54.0,46.0,68.0,51.0,44.0,25.0,41.0,16.0,7.0,12.0
18178,18178,L. Wahlstedt,18,Sweden,48,65,Dalkurd FF,€50K,Right,1.0,...,28.0,15.0,48.0,20.0,38.0,20.0,18.0,11.0,45.0,51.0
18179,18179,J. Williams,17,England,48,64,Northampton Town,€50K,Right,1.0,...,59.0,38.0,70.0,55.0,54.0,47.0,27.0,51.0,11.0,8.0
18180,18180,M. Hurst,22,Scotland,48,58,St. Johnstone FC,€40K,Right,1.0,...,42.0,25.0,55.0,33.0,58.0,20.0,20.0,15.0,50.0,45.0
18181,18181,C. Maher,17,Republic of Ireland,48,66,Bray Wanderers,€50K,Right,1.0,...,57.0,39.0,59.0,60.0,48.0,53.0,37.0,49.0,9.0,10.0
18182,18182,Y. Góez,18,Colombia,48,65,Atlético Nacional,€50K,Right,1.0,...,62.0,40.0,61.0,54.0,48.0,50.0,45.0,42.0,8.0,6.0
18183,18183,K. Pilkington,44,England,48,48,Cambridge United,€0,Right,1.0,...,17.0,23.0,45.0,22.0,44.0,24.0,11.0,15.0,49.0,46.0
18184,18184,D. Horton,18,England,48,55,Lincoln City,€40K,Right,1.0,...,57.0,47.0,64.0,59.0,66.0,53.0,46.0,49.0,14.0,15.0
18185,18185,E. Tweed,19,Republic of Ireland,48,59,Derry City,€50K,Right,1.0,...,61.0,47.0,60.0,60.0,43.0,52.0,49.0,39.0,5.0,8.0
18186,18186,Zhang Yufeng,20,China PR,47,64,Beijing Renhe FC,€60K,Right,1.0,...,70.0,42.0,55.0,46.0,60.0,55.0,50.0,41.0,6.0,8.0
18187,18187,C. Ehlich,19,Germany,47,59,SpVgg Unterhaching,€40K,Right,1.0,...,62.0,44.0,69.0,61.0,59.0,38.0,38.0,42.0,15.0,12.0
18188,18188,L. Collins,17,Wales,47,62,Newport County,€60K,Right,1.0,...,72.0,49.0,61.0,33.0,40.0,36.0,47.0,38.0,13.0,10.0
18189,18189,A. Kaltner,18,Germany,47,61,SpVgg Unterhaching,€60K,Right,1.0,...,66.0,38.0,81.0,55.0,60.0,28.0,41.0,15.0,12.0,8.0
18190,18190,L. Watkins,18,England,47,67,Cambridge United,€60K,Right,1.0,...,55.0,41.0,54.0,61.0,55.0,44.0,54.0,44.0,10.0,8.0
18191,18191,J. Norville-Williams,18,England,47,65,Cambridge United,€50K,Left,1.0,...,52.0,26.0,61.0,38.0,55.0,55.0,39.0,42.0,14.0,12.0
18192,18192,S. Squire,18,England,47,64,Cambridge United,€50K,Right,1.0,...,66.0,41.0,61.0,55.0,59.0,55.0,45.0,41.0,12.0,13.0
18193,18193,N. Fuentes,18,Chile,47,64,Unión Española,€50K,Right,1.0,...,58.0,22.0,56.0,54.0,40.0,48.0,30.0,48.0,12.0,11.0
18194,18194,J. Milli,18,Italy,47,65,Lecce,€50K,Right,1.0,...,14.0,22.0,33.0,15.0,59.0,17.0,28.0,10.0,40.0,44.0
18195,18195,S. Griffin,18,Republic of Ireland,47,67,Waterford FC,€60K,Right,1.0,...,58.0,53.0,62.0,54.0,49.0,51.0,40.0,37.0,7.0,13.0
18196,18196,K. Fujikawa,19,Japan,47,61,Júbilo Iwata,€60K,Right,1.0,...,58.0,42.0,63.0,35.0,51.0,55.0,51.0,44.0,11.0,8.0
18197,18197,D. Holland,18,Republic of Ireland,47,61,Cork City,€60K,Right,1.0,...,62.0,50.0,55.0,50.0,38.0,37.0,48.0,47.0,10.0,15.0
18198,18198,J. Livesey,18,England,47,70,Burton Albion,€60K,Right,1.0,...,24.0,26.0,56.0,20.0,38.0,25.0,37.0,11.0,42.0,48.0
18199,18199,M. Baldisimo,18,Canada,47,69,Vancouver Whitecaps FC,€70K,Right,1.0,...,63.0,49.0,57.0,42.0,43.0,53.0,40.0,49.0,14.0,15.0
18200,18200,J. Young,18,Scotland,47,62,Swindon Town,€60K,Left,1.0,...,48.0,44.0,77.0,31.0,31.0,26.0,37.0,17.0,12.0,11.0
18201,18201,D. Walsh,18,Republic of Ireland,47,68,Waterford FC,€60K,Left,1.0,...,52.0,39.0,74.0,39.0,52.0,44.0,31.0,47.0,11.0,13.0
18202,18202,J. Lundstram,19,England,47,65,Crewe Alexandra,€60K,Right,1.0,...,57.0,43.0,55.0,40.0,47.0,46.0,52.0,48.0,8.0,9.0
18203,18203,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,€60K,Right,1.0,...,39.0,41.0,47.0,43.0,67.0,47.0,33.0,15.0,5.0,12.0
18204,18204,B. Worman,16,England,47,67,Cambridge United,€60K,Right,1.0,...,69.0,45.0,60.0,55.0,32.0,32.0,43.0,13.0,6.0,13.0
18205,18205,D. Walker-Rice,17,England,47,66,Tranmere Rovers,€60K,Right,1.0,...,60.0,64.0,42.0,40.0,48.0,33.0,47.0,25.0,8.0,9.0
18206,18206,G. Nugent,16,England,46,66,Tranmere Rovers,€60K,Right,1.0,...,55.0,43.0,62.0,47.0,60.0,56.0,49.0,43.0,12.0,9.0

In [3]:
del fifa["Unnamed: 0"]

In [4]:
fifa.fillna(method="bfill", inplace=True)

In [5]:
pays = fifa['Nationality'].unique()
npays = range(len( fifa['Nationality'].unique()))
apays = dict(zip(pays, npays))

In [6]:
club = fifa['Club'].unique()
nclub = range(len( fifa['Club'].unique()))
aclub = dict(zip(club, nclub))

In [7]:
foot = {"Left":1, "Right":2}

In [8]:
rate = {'Medium/ Medium':1, 'High/ Low':2, 'High/ Medium':3, 'High/ High':4,
       'Medium/ High':5, 'Medium/ Low':6, 'Low/ High':7, 'Low/ Medium':8,
       'Low/ Low':9}

In [9]:
position = {'RF':1, 'ST':2, 'LW':3, 'GK':4, 'RCM':5, 'LF':6, 'RS':7, 'RCB':8, 'LCM':9, 'CB':10,
       'LDM':11, 'CAM':12, 'CDM':13, 'LS':14, 'LCB':15, 'RM':16, 'LAM':17, 'LM':18, 'LB':19, 'RDM':20,
       'RW':21, 'CM':22, 'RB':23, 'RAM':24, 'CF':25, 'RWB':26, 'LWB':27}

In [ ]:
fifa['Joined'] = pd.to_datetime(fifa['Joined'])

In [ ]:
fifa["Height"] = fifa["Height"].str.replace("'",'.').astype(float)
fifa["Height"] = round(fifa["Height"]*0.3048,2)

In [ ]:
fifa["Weight"] = fifa["Weight"].str.replace("lbs",'')
fifa["Weight"] = round(fifa["Weight"].astype(float)*0.4535,2)

In [ ]:
fifa['Nationality'] = fifa['Nationality'].map(apays)

In [ ]:
fifa['Club'] = fifa['Club'].map(aclub)

In [ ]:
fifa["Preferred Foot"] = fifa["Preferred Foot"].map(foot)

In [ ]:
fifa["Position"] = fifa["Position"].map(position)

In [ ]:
fifa["Work Rate"] = fifa["Work Rate"].map(rate)

In [ ]:
fifa["Joined"] = fifa["Joined"].astype(str)
fifa["Joined"] = fifa["Joined"].str.extract("([\d]{4})")

In [ ]:
fifa["Contract Valid Until"] = pd.to_datetime(fifa["Contract Valid Until"])
fifa["Contract Valid Until"] = fifa["Contract Valid Until"].astype(str)
fifa["Contract Valid Until"] = fifa["Contract Valid Until"].str.extract("([\d]{4})")

In [10]:
class Nettoyage(pd.core.frame.DataFrame):
    
    def __init__(self, df):
        pd.core.frame.DataFrame.__init__(self,df)
        
    def erase(self,col):
        del self[col]
        return self
    
    def fil_nan(self):
        fillna = self.fillna(method="bfill", inplace=True)
        return fillna
    
    def mapping(self, col, dico):
        self[col] = self[col].map(dico)
        
    def converth(self,col):
        self[col] = round(self[col]*0.3048,2)
        return self[col]
        
    def convertw(self,col):
        self[col] = round(self[col]*0.4535,2)
        return self[col]
    
    def replacestr(self,col, val1, val2):
        self[col] = self[col].str.replace(val1,val2)
        return self[col]
    
    def dico(self, col):
        a = self[col].unique()
        b = range(len(self[col].unique()))
        c = dict(zip(a, b))
        return c
    
    def date(self, col):
        self[col] = pd.to_datetime(self[col])
        
    def astype(self,col,typ):
        try:
            self[col] = self[col].astype(typ)
        except:
            self[col] = self[col].str.replace("'",".").astype(typ)
        return self[col]
        
    def extract(self,col, string):
        self[col] = self[col].str.extract(string)
        return self[col]

In [11]:
test = pd.read_csv("Test.csv")

In [12]:
test = Nettoyage(test)
fifa = Nettoyage(fifa)

In [13]:
test.mapping("Club", aclub)
fifa.mapping("Club", aclub)

In [14]:
test.mapping("Nationality", apays)
fifa.mapping("Nationality", apays)

In [15]:
test.mapping("Preferred Foot", foot)
fifa.mapping("Preferred Foot", foot)

In [16]:
test.mapping("Position", position)
fifa.mapping("Position", position)

In [17]:
test.mapping("Work Rate", rate)
fifa.mapping("Work Rate", rate)

In [18]:
test.date("Joined")
test.astype("Joined", str)
test.extract("Joined","([\d]{4})")

fifa.date("Joined")
fifa.astype("Joined", str)
fifa.extract("Joined","([\d]{4})")

0        2004
1        2018
2        2017
3        2011
4        2015
5        2012
6        2012
7        2014
8        2005
9        2014
10       2014
11       2014
12       2010
13       2010
14       2016
15       2015
16       2010
17       2014
18       2014
19       2018
20       2008
21       2013
22       2011
23       2011
24       2005
25       2018
26       2017
27       2013
28       2010
29       2010
         ...
18177    2016
18178    2018
18179    2018
18180    2013
18181    2017
18182    2018
18183    2018
18184    2017
18185    2018
18186    2016
18187    2017
18188    2017
18189    2017
18190    2018
18191    2018
18192    2018
18193    2018
18194    2018
18195    2018
18196    2017
18197    2018
18198    2018
18199    2018
18200    2015
18201    2018
18202    2017
18203    2018
18204    2017
18205    2018
18206    2018
Name: Joined, Length: 18207, dtype: object

In [19]:
test.date("Contract Valid Until")
test.astype("Contract Valid Until", str)
test.extract("Contract Valid Until","([\d]{4})")

fifa.date("Contract Valid Until")
fifa.astype("Contract Valid Until", str)
fifa.extract("Contract Valid Until","([\d]{4})")

fifa.astype("Contract Valid Until", float)
test.astype("Contract Valid Until", float)

fifa.astype("Joined", float)
test.astype("Joined", float)

0    2017.0
1    2013.0
2    2017.0
3    2016.0
4    2016.0
5    2011.0
Name: Joined, dtype: float64

In [20]:

test.astype("Height", float)
test.converth("Height")

fifa.astype("Height", float)
fifa.converth("Height")

0        1.74
1        1.89
2        1.80
3        1.95
4        1.56
5        1.77
6        1.77
7        1.83
8        1.83
9        1.89
10       1.83
11       1.83
12       1.89
13       1.77
14       1.71
15       1.55
16       1.89
17       1.80
18       1.89
19       2.01
20       1.89
21       1.86
22       1.95
23       1.77
24       1.89
25       1.55
26       1.80
27       1.86
28       1.56
29       1.65
         ...
18177    1.55
18178    1.83
18179    1.89
18180    1.86
18181    1.56
18182    1.55
18183    1.89
18184    1.86
18185    1.56
18186    1.55
18187    1.55
18188    1.55
18189    1.55
18190    1.80
18191    1.56
18192    1.86
18193    1.77
18194    1.92
18195    1.77
18196    1.74
18197    1.55
18198    1.56
18199    1.71
18200    1.80
18201    1.86
18202    1.80
18203    1.92
18204    1.77
18205    1.55
18206    1.55
Name: Height, Length: 18207, dtype: float64

In [21]:
test.replacestr("Weight", "lbs", "")
test.astype("Weight", float)
test.convertw("Weight")

fifa.replacestr('Value','€',"")
fifa.replacestr('Value','.',"")
fifa.replacestr('Value','M',"000000")
fifa.replacestr('Value','K',"000")

fifa.replacestr("Weight", "lbs", "")
fifa.astype("Weight", float)
fifa.convertw("Weight")

0        72.11
1        82.99
2        68.03
3        76.19
4        69.84
5        73.92
6        66.21
7        86.16
8        82.08
9        87.07
10       79.82
11       76.19
12       78.00
13       67.12
14       72.11
15       74.83
16       88.89
17       73.01
18       84.80
19       96.14
20       76.19
21       77.10
22       92.06
23       69.84
24       84.80
25       73.01
26       71.20
27       83.90
28       78.00
29       58.96
         ...
18177    73.92
18178    79.82
18179    73.92
18180    78.00
18181    60.77
18182    74.83
18183    86.16
18184    81.18
18185    72.11
18186    78.91
18187    73.01
18188    67.12
18189    74.83
18190    79.82
18191    76.19
18192    74.83
18193    66.21
18194    84.80
18195    63.94
18196    66.21
18197    63.94
18198    69.84
18199    68.03
18200    71.20
18201    76.19
18202    60.77
18203    77.10
18204    67.12
18205    69.84
18206    79.82
Name: Weight, Length: 18207, dtype: float64

In [22]:
col=['Name','Value']


del test['Name']
del fifa['Name']
y= fifa['Value']
del test['Value']
del fifa['Value']

X=fifa

In [23]:
y

0        1105000000
1          77000000
2        1185000000
3          72000000
4         102000000
5          93000000
6          67000000
7          80000000
8          51000000
9          68000000
10         77000000
11        765000000
12         44000000
13         60000000
14         63000000
15         89000000
16        835000000
17         78000000
18         58000000
19        535000000
20        515000000
21         60000000
22         38000000
23        645000000
24         27000000
25         81000000
26        695000000
27        595000000
28        695000000
29         62000000
            ...
18177         70000
18178         50000
18179         50000
18180         40000
18181         50000
18182         50000
18183             0
18184         40000
18185         50000
18186         60000
18187         40000
18188         60000
18189         60000
18190         60000
18191         50000
18192         50000
18193         50000
18194         50000
18195         60000
18196         60000
18197         60000
18198         60000
18199         70000
18200         60000
18201         60000
18202         60000
18203         60000
18204         60000
18205         60000
18206         60000
Name: Value, Length: 18207, dtype: object

### ML

In [24]:
y=y.astype(float)

In [25]:
import numpy as np
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)

In [26]:
import xgboost as xgb
import math
model=xgb.XGBRegressor(max_depth=20,n_estimators=200)

In [27]:
model.fit(X_train, y_train)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=20, min_child_weight=1, missing=None, n_estimators=200,
       n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)

In [28]:
from sklearn.metrics import mean_squared_error
y_pred = model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
print("MSE: %.4f" % mse)

print('Mediane : ',math.sqrt((((y_pred)-(y_test))**2).median()))

MSE: 611363131256843.3750
Mediane :  28564.25

In [29]:
print('Erreur %: ',math.sqrt((((y_pred)-(y_test))**2).median())/y_pred.mean())

Erreur %:  0.002258651082184401

In [30]:
y_pred_P12 = model.predict(test)

In [31]:
y_pred_P12

array([1.6488620e+07, 9.8972248e+07, 1.7236288e+08, 3.0569924e+07,
       1.8286296e+08, 5.3292212e+07], dtype=float32)

In [32]:
test['pred']=y_pred_P12
test

,Age,Nationality,Overall,Potential,Club,Preferred Foot,International Reputation,Weak Foot,Skill Moves,Work Rate,...,ShotPower,Jumping,Stamina,Strength,Aggression,Vision,StandingTackle,GKPositioning,GKReflexes,pred
0,29,10,75,75,2,1,1,1,2,4,...,90,65,60,95,70,50,60,20,20,16488620.0
1,22,10,90,96,18,2,2,4,3,4,...,90,90,90,90,60,85,55,20,20,98972248.0
2,34,10,90,85,19,1,2,4,4,4,...,90,90,90,90,90,90,90,90,90,172362880.0
3,19,10,70,90,2,2,1,1,2,4,...,90,80,70,60,80,60,50,70,80,30569924.0
4,29,79,89,90,12,2,0,3,4,4,...,90,80,70,70,60,90,50,70,80,182862960.0
5,22,9,76,80,12,2,2,2,3,3,...,72,65,71,59,90,78,64,50,67,53292212.0